[project]
name = "satctl"
version = "0.2.0"
description = "Toolkit to search, download and process Earth Observation data"
readme = "README.md"
authors = [
    { name = "Edoardo Arnaudo", email = "edoardo.arnaudo@linksfoundation.com" },
    { name = "Luca Barco", email = "andrea.bragagnolo@linksfoundation.com" },
    { name = "Andrea Bragagnolo", email = "luca.barco@linksfoundation.com" },
    { name = "Gaetano Chiriaco", email = "gaetano.chiriaco@linksfoundation.com" },
]
requires-python = ">=3.10"
dependencies = [
    "boto3>=1.28.0",
    "bottleneck>=1.6.0",
    "earthaccess>=0.14.0",
    "envyaml>=1.10.211231",
    "eumdac>=3.0.0",
    "geojson-pydantic>=2.1.0",
    "h5netcdf>=1.7.3",
    "h5py>=3.15.1",
    "netcdf4>=1.7.2",
    "odc-stac>=0.4.0",
    "pydantic>=2.11.9",
    "pydantic-settings>=2.10.1",
    "pyhdf>=0.11.6",
    "pyproj>=3.7.1",
    "pyresample>=1.31.0",
    "pyspectral>=0.13.6",
    "pystac>=1.14.1",
    "pystac-client>=0.9.0",
    "rioxarray>=0.19.0",
    "satpy>=0.58.0",
    "shapely>=2.1.1",
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Scientific/Engineering :: GIS",
    "Topic :: Software Development :: Libraries",
]

[project.optional-dependencies]
console = ["rich>=14.1.0", "typer>=0.19.2"]
dev = ["mkdocs-material>=9.6.22", "pyright>=1.1.406", "ruff>=0.13.2"]
test = ["pytest>=8.4.2", "pytest-cov>=7.0.0"]

[project.scripts]
satctl = "satctl.cli:app"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff]
line-length = 119

[tool.pytest.ini_options]
markers = [
    "integration: marks tests as integration tests (require real APIs and credentials)",
    "requires_credentials: requires real API credentials from environment",
    "slow: marks tests as slow running (>5 seconds)",
]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
