name: test

on:
  push:
    branches:
      - main

env:
  UV_FROZEN: true
  FORCE_COLOR: 1

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint ${{ matrix.python-version }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.13", "3.14"]
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup UV
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: uv sync --all-extras
      - name: Lint
        run: make lint

  test:
    runs-on: ubuntu-latest
    name: Test ${{ matrix.python-version }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup UV
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: uv sync --all-extras
      - name: Test
        run: make test
